### PR TITLE
Lf textmining

### PR DESCRIPTION
**Pull request by LucaFumis**
WIP textmining api endpoints.
It queries our API and then EPMC, then merges the results.
Working so far, but needs pagination server side: not sure how to pass paging parameters (`size` and `from`).

### CODE REVIEW

**Comment by LucaFumis** [comment]
I've added `from` and `size` as optional parameters to the evidence query: ideally those would be added to the textmining part only...

**Comment by LucaFumis** [comment]
This is now working with pagination.
Might need option for sorting, but probably good to start getting some feedback - I don't want it to become too large for review.

**Comment by LucaFumis** [comment]
Need to add params/options for sorting so can hold off review and merging.

**Comment by LucaFumis** [comment]
Ready for review.

**Comment by LucaFumis** [comment]
Ready for review.

**Review by mirandaio — APPROVED** [review]

**Pull request merged**
